apiVersion: v1
kind: Service
metadata:
  name: wordpress                      #Give suitable name as you want for service
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim                      #Give suitable name as you want        
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi                       #Increase size as your need
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress                        #Give suitable name as you want
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache        #you can change wordpress ami
        name: wordpress         #Give suitable name as you want for ec2 instance
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password            #this password that we store in secretbox
        ports:
        - containerPort: 80
          name: wordpress                  
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html         #Don't change path
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim       #this name is same as mention above for pvc
